- hosts: 172.31.15.250
  become: yes
  tasks:
    - name: to install apache server
      yum:
        name: httpd
        state: present
    - name: to copy index.html
      copy: 
          src: index.html
          dest: /var/www/html
    - name: start and enable
      service:
        name: httpd
        state: started
        enabled: yes
    
          
